### PR TITLE
Revert "Add script type setting to elasticsearch cluster"

### PR DESCRIPTION
**Pull request by aditimarkale**
Reverts Datatamer/terraform-aws-es#11

`script.allowed_types` is not supported by AWS ES

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
Looks good :')

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — APPROVED** [review]

**Pull request merged**
