### PR TITLE
DEV-14729 - Fixes a deprecation warning about interpolation-only expressions

### PR DESCRIPTION
**Pull request by souza-dan**
Spotted this deprecation warning when working on the config module:
```
Warning: Interpolation-only expressions are deprecated

  on .terraform/modules/tamr-es-cluster/main.tf line 8, in module "tamr-es-cluster":
   8:   security_group_ids              = ["${module.elasticsearch-sg.es_security_group_id}"]

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


```

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by schwartzmanb — APPROVED** [review]

**Pull request merged**
