### PR TITLE
Add script type setting to elasticsearch cluster

### PR DESCRIPTION
**Pull request by aditimarkale**
Testbed test running using elasticsearch cluster fails with the following error :
```"UnifyElasticSearchDataCluster":{"healthy":false,"message":"Cluster Status: GREEN but [script.allowed_types] must be set to [[inline]] for all nodes in the cluster. Current value is [[]]"```

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — APPROVED** [review]
Looks good!

**Comment by souza-dan** [comment]
Reminder to increment version and update changelog.

**Review by daniosim — APPROVED** [review]
Looks good! 

Just curious, if you upgrade to the version with this change, would this be an in-place change?

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by aditimarkale** [comment]
> Looks good!
> 
> Just curious, if you upgrade to the version with this change, would this be an in-place change?

It should be an in-place change

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Pull request merged**
